[package]
name = "tree-sitter-parse"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
libc = "0.2"
libloading = "0.6"
tree-sitter = "0.17"

[build-dependencies]
cc = "1.0"
rustc_tools_util = "0.2"
